{
    "update_id": 193532786,
    "message": {
        "message_id": 333,
        "date": 1597264379,
        "chat": {
            "id": 90821763,
            "type": "private",
            "username": "wesleyjcr",
            "first_name": "Wesley",
        },
        "text": "/resumo",
        "entities": [{"type": "bot_command", "offset": 0, "length": 7}],
        "caption_entities": [],
        "photo": [],
        "new_chat_members": [],
        "new_chat_photo": [],
        "delete_chat_photo": False,
        "group_chat_created": False,
        "supergroup_chat_created": False,
        "channel_chat_created": False,
        "from": {
            "id": 90821763,
            "first_name": "Wesley",
            "is_bot": False,
            "username": "wesleyjcr",
            "language_code": "pt-br",
        },
    },
}
